# Choosing the Right Data Structure

## Lists: Ordered Sequence

A list of token IDs


In [1]:
token_ids = [101, 7592, 1010, 2129, 2024, 2017, 102]
print(token_ids)


[101, 7592, 1010, 2129, 2024, 2017, 102]


A batch of embedding vectors


In [2]:
embeddings = [
    [0.12, -0.34, 0.56, 0.78],
    [0.91, -0.23, 0.45, 0.67],
    [0.33, -0.11, 0.89, 0.22],
]
print(embeddings)

results = []
results.append({"prompt": "What is RAG?", "response": "...", "score": 0.85})
results.append({"prompt": "Explain embeddings", "response": "...", "score": 0.92})
print(results)


[[0.12, -0.34, 0.56, 0.78], [0.91, -0.23, 0.45, 0.67], [0.33, -0.11, 0.89, 0.22]]
[{'prompt': 'What is RAG?', 'response': '...', 'score': 0.85}, {'prompt': 'Explain embeddings', 'response': '...', 'score': 0.92}]


## Dicts: Configuration and Mapping


In [3]:
model_config = {
    "model": "large-model",
    "temperature": 0.7,
    "max_output_tokens": 1024,
    "top_p": 0.9,
}
print(model_config)

vocab = {"hello": 7592, "world": 2088, "[CLS]": 101, "[SEP]": 102}
print(vocab)

token_id = vocab.get("unknown_word", 0)
print(token_id)


{'model': 'large-model', 'temperature': 0.7, 'max_output_tokens': 1024, 'top_p': 0.9}
{'hello': 7592, 'world': 2088, '[CLS]': 101, '[SEP]': 102}
0


## Sets: Deduplication and Fast Lookup


In [4]:
stopwords = {"the", "a", "an", "is", "at", "in", "on", "and", "or"}

tokens = ["the", "cat", "is", "on", "the", "mat"]
filtered = [t for t in tokens if t not in stopwords]
print(filtered)  # ['cat', 'mat']

unique_words = set(["apple", "banana", "apple", "cherry", "banana"])
print(unique_words)  # Print order is not guaranteed


['cat', 'mat']
{'apple', 'banana', 'cherry'}


## Tuples: Immutable and Hashable

In [5]:
image_shape = (3, 224, 224)  # channels, height, width

embedding_cache = {}
embedding_cache[(0.1, 0.2, 0.3)] = "document_42"

def evaluate_model(predictions, labels):
    precision = 0.91
    recall = 0.87
    f1 = 0.89
    return precision, recall, f1

predictions = ["positive", "negative", "positive"]
labels = ["positive", "negative", "negative"]
p, r, f1 = evaluate_model(predictions, labels)
print(p, r, f1)


0.91 0.87 0.89


# Comprehensions: Data Processing in One Line


## List Comprehensions


In [6]:
raw_scores = [0.2, 0.8, 0.5, 0.1, 0.9]
min_val, max_val = min(raw_scores), max(raw_scores)
normalized = [(s - min_val) / (max_val - min_val) for s in raw_scores]
print(normalized)

predictions = [
    {"label": "positive", "score": 0.95},
    {"label": "negative", "score": 0.42},
    {"label": "positive", "score": 0.88},
    {"label": "neutral", "score": 0.31},
]
confident = [p for p in predictions if p["score"] > 0.5]
print(confident)

labels = [p["label"] for p in confident]
print(labels)  # ['positive', 'positive']


[0.125, 0.875, 0.5, 0.0, 1.0]
[{'label': 'positive', 'score': 0.95}, {'label': 'positive', 'score': 0.88}]
['positive', 'positive']


## Dict Comprehensions


In [7]:
words = ["hello", "world", "embedding", "vector", "token"]
word_to_idx = {word: idx for idx, word in enumerate(words)}
print(word_to_idx)

idx_to_word = {idx: word for word, idx in word_to_idx.items()}
print(idx_to_word)

config = {
    "model": "large-model",
    "temperature": 0.7,
    "max_output_tokens": 1024,
    "stream": True,
}
numeric_params = {
    k: v
    for k, v in config.items()
    if isinstance(v, (int, float)) and not isinstance(v, bool)
}
print(numeric_params)


{'hello': 0, 'world': 1, 'embedding': 2, 'vector': 3, 'token': 4}
{0: 'hello', 1: 'world', 2: 'embedding', 3: 'vector', 4: 'token'}
{'temperature': 0.7, 'max_output_tokens': 1024}


## Set Comprehensions


In [8]:
dataset = [
    {"text": "Great product!", "label": "positive"},
    {"text": "Terrible service", "label": "negative"},
    {"text": "It was okay", "label": "neutral"},
    {"text": "Love it!", "label": "positive"},
]
unique_labels = {item["label"] for item in dataset}
print(unique_labels)  # Print order varies


{'positive', 'neutral', 'negative'}


# Tuple Unpacking and Multiple Returns


## Basic Unpacking


In [9]:
point = (3, 7)
x, y = point

pairs = [("cat", 0.95), ("dog", 0.82), ("bird", 0.71)]
for animal, score in pairs:
    print(f"{animal}: {score}")

model_name, _, version = ("model-family", "unused", "v2")
print(model_name, version)


cat: 0.95
dog: 0.82
bird: 0.71
model-family v2


## Star Unpacking


In [10]:
scores = [0.95, 0.88, 0.76, 0.71, 0.65]
best, *middle, worst = scores
print(best, middle, worst)

lines = ["name,score,label", "doc1,0.95,positive", "doc2,0.42,negative"]
header, *data_rows = lines
print(header)
print(data_rows)


0.95 [0.88, 0.76, 0.71] 0.65
name,score,label
['doc1,0.95,positive', 'doc2,0.42,negative']


## Functions Returning Multiple Values


In [11]:
def train_epoch():
    loss = 0.342
    accuracy = 0.891
    num_samples = 1024
    return loss, accuracy, num_samples

loss, acc, n = train_epoch()
print(f"Loss: {loss:.3f}, Accuracy: {acc:.1%}, Samples: {n}")


Loss: 0.342, Accuracy: 89.1%, Samples: 1024


# F-Strings: Clean Formatting


In [12]:
model = "large-model"
tokens = 1523
cost = 0.00457

print(f"Model: {model}, Tokens: {tokens}, Cost: ${cost}")

print(f"Cost: ${cost:.4f}")          # 4 decimal places: $0.0046
print(f"Accuracy: {0.8912:.1%}")     # Percentage: 89.1%
print(f"Tokens: {tokens:,}")         # Thousands separator: 1,523
print(f"{'Model':<20} {'Score':>10}")  # Alignment example

scores = [0.9, 0.85, 0.78]
print(f"Average: {sum(scores)/len(scores):.2f}")  # Average: 0.84


Model: large-model, Tokens: 1523, Cost: $0.00457
Cost: $0.0046
Accuracy: 89.1%
Tokens: 1,523
Model                     Score
Average: 0.84


# Slicing: Working with Sequences


In [13]:
tokens = ["[CLS]", "how", "does", "RAG", "work", "?", "[SEP]"]

content = tokens[1:-1]
print(content)

first_three = tokens[:3]
print(first_three)

last_two = tokens[-2:]
print(last_two)

every_other = tokens[::2]
print(every_other)

reversed_tokens = tokens[::-1]
print(reversed_tokens)


['how', 'does', 'RAG', 'work', '?']
['[CLS]', 'how', 'does']
['?', '[SEP]']
['[CLS]', 'does', 'work', '[SEP]']
['[SEP]', '?', 'work', 'RAG', 'does', 'how', '[CLS]']


## Why Slicing Matters for AI


In [14]:
import numpy as np

embeddings = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
])

batch = embeddings[:2]
print(batch)

reduced = embeddings[:, :3]
print(reduced)


[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]
[[0.1 0.2 0.3]
 [0.5 0.6 0.7]
 [0.9 1.  1.1]]


## String Slicing


In [15]:
prompt = "Explain how transformers work in simple terms"

truncated = prompt[:20]
print(truncated)

filename = "model_weights.safetensors"
extension = filename[filename.rfind("."):]
print(extension)


Explain how transfor
.safetensors


# The Walrus Operator :=


In [16]:
documents = [
    {"text": "Document 1", "score": 0.95},
    {"text": "Document 2", "score": 0.82},
    {"text": "Document 3", "score": 0.71}
]

for doc in documents:
    if(score:= doc["score"]) > 0.8:
        print(f"High scoring document: {doc['text']} with score {score}")


High scoring document: Document 1 with score 0.95
High scoring document: Document 2 with score 0.82


# Essential Python Idioms


## enumerate: Loop with Index


In [17]:
documents = ["intro to RAG", "embedding models", "vector databases"]

for i in range(len(documents)):
    print(f"Doc {i}: {documents[i]}")

for i, doc in enumerate(documents):
    print(f"Doc {i}: {doc}")

for i, doc in enumerate(documents, start=1):
    print(f"Doc {i}: {doc}")


Doc 0: intro to RAG
Doc 1: embedding models
Doc 2: vector databases
Doc 0: intro to RAG
Doc 1: embedding models
Doc 2: vector databases
Doc 1: intro to RAG
Doc 2: embedding models
Doc 3: vector databases


## zip: Iterate in Parallel


In [18]:
models = ["large-model", "balanced-model", "small-local-model"]
scores = [0.92, 0.89, 0.85]
latencies = [1.2, 1.8, 0.6]

for model, score, latency in zip(models, scores, latencies):
    print(f"{model}: score={score}, latency={latency}s")

model_scores = dict(zip(models, scores))
print(model_scores)


large-model: score=0.92, latency=1.2s
balanced-model: score=0.89, latency=1.8s
small-local-model: score=0.85, latency=0.6s
{'large-model': 0.92, 'balanced-model': 0.89, 'small-local-model': 0.85}


## any and all: Bulk Boolean Checks


In [19]:
scores = [0.95, 0.88, 0.42, 0.76]

has_high_score = any(s > 0.9 for s in scores)  # True
print(has_high_score)

all_passing = all(s > 0.5 for s in scores)  # False (0.42 fails)
print(all_passing)

required = ["model", "temperature", "max_output_tokens"]
config = {"model": "large-model", "temperature": 0.7}
missing = [f for f in required if f not in config]
has_missing = any(f not in config for f in required)  # True
print(missing)
print(has_missing)


True
False
['max_output_tokens']
True


## sorted with key: Custom Sorting


In [20]:
results = [
    {"doc": "RAG tutorial", "score": 0.72},
    {"doc": "Vector DB guide", "score": 0.95},
    {"doc": "Embedding basics", "score": 0.88},
]
ranked = sorted(results, key=lambda r: r["score"], reverse=True)
print(ranked)

words = ["transformer", "RAG", "embedding", "LLM"]
by_length = sorted(words, key=len)
print(by_length)


[{'doc': 'Vector DB guide', 'score': 0.95}, {'doc': 'Embedding basics', 'score': 0.88}, {'doc': 'RAG tutorial', 'score': 0.72}]
['RAG', 'LLM', 'embedding', 'transformer']


## dict.get with Defaults


In [21]:
config = {"model": "large-model", "temperature": 0.7}


This would raise KeyError if the key is missing:
max_output_tokens = config["max_output_tokens"]


In [22]:
max_output_tokens = config.get("max_output_tokens", 1024)
stream = config.get("stream", False)          # False
print(max_output_tokens, stream)


1024 False


# String Methods for NLP and Text Processing


## split and join: Tokenization Basics


In [23]:
text = "How does retrieval augmented generation work?"
tokens = text.split()
print(tokens)

csv_line = "positive,0.95,This product is great"
label, score, text = csv_line.split(",", maxsplit=2)
print(label, score, text)

cleaned_tokens = ["how", "does", "rag", "work"]
sentence = " ".join(cleaned_tokens)
print(sentence)

items = ["retrieval", "augmented", "generation"]
formatted = ", ".join(items)
print(formatted)


['How', 'does', 'retrieval', 'augmented', 'generation', 'work?']
positive 0.95 This product is great
how does rag work
retrieval, augmented, generation


## strip, replace, lower: Cleaning Text


In [24]:
raw_response = "\n  The answer is 42.  \n\n"
clean = raw_response.strip()
print(clean)

query = "What is RAG?"
normalized = query.lower()
print(normalized)

text = "Hello\nWorld\n\nHow are you?"
single_line = text.replace("\n", " ")
print(single_line)

dirty = "  \n HELLO, WORLD! \t "
clean = dirty.strip().lower().replace("!", "")
print(clean)


The answer is 42.
what is rag?
Hello World  How are you?
hello, world


## startswith and endswith: Pattern Matching


In [25]:
filename = "model_weights.safetensors"

if filename.endswith(".safetensors"):
    print("SafeTensors format")

if filename.endswith((".pt", ".pth", ".safetensors")):
    print("Model weights file")

model_files = ["encoder.onnx", "ranker.pt", "tokenizer.json", "weights.safetensors"]
weight_files = [
    name
    for name in model_files
    if name.endswith((".pt", ".safetensors"))
]
print(weight_files)


SafeTensors format
Model weights file
['ranker.pt', 'weights.safetensors']


# Ternary Expressions


In [26]:
score = 0.85


## Ternary expression


In [27]:
label = "high confidence" if score > 0.8 else "low confidence"
print(label)

use_large_model = True
model = "large-model" if use_large_model else "small-model"
print(model)

user_temperature = None
temperature = user_temperature if user_temperature is not None else 0.7
print(temperature)

for name, val in [("accuracy", 0.92), ("loss", 0.45)]:
    status = "good" if val > 0.8 else "needs work"
    print(f"{name}: {val} ({status})")


high confidence
large-model
0.7
accuracy: 0.92 (good)
loss: 0.45 (needs work)


# None Checks and Truthiness


None, Fasle, 0, 0.0, empty string, empty list, empty dict are all considered False in Python

The Difference Between is None and Truthiness


In [28]:
# def get_embedding(text, model=None):
#     if model is None:
#         model = "text-embedding-3-small"
#     return compute_embedding(text, model)

# def process_scores(scores=None):
#     if scores is None:
#         scores = []
#     return scores

# results = []
# if not results:
#     print("No results found")

# response = api_call()
# if response:
#     process(response)

The Common Pattern: Default Mutable Arguments
The problem with the first version is that the default [] is created once when the function is defined, not each time it is called. 
Every call without an explicit collection argument shares and mutates the same list.

In [29]:
# def add_document(doc, collection=[]):
#     collection.append(doc)
#     return collection

# def add_document(doc, collection=None):
#     if collection is None:
#         collection = []
#     collection.append(doc)
#     return collection